CREATE DATABASE IF NOT EXISTS `FILES` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `FILES`;

CREATE TABLE `USER` (
  `id` VARCHAR(42),
  `sender_email` VARCHAR(42),
  `receiver_email` VARCHAR(42),
  `message` VARCHAR(42),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `BIND_USER_FILES` (
  `id` VARCHAR(42),
  `id_1` VARCHAR(42),
  `id_2` VARCHAR(42),
  `id_user` VARCHAR(42),
  `id_file` VARCHAR(42),
  PRIMARY KEY (`id`, `id_1`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `FILES` (
  `id` VARCHAR(42),
  `file_name` VARCHAR(42),
  `file_size` VARCHAR(42),
  `upload_date` VARCHAR(42),
  `delete_date` VARCHAR(42),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `BIND_USER_FILES` ADD FOREIGN KEY (`id_1`) REFERENCES `FILES` (`id`);
ALTER TABLE `BIND_USER_FILES` ADD FOREIGN KEY (`id`) REFERENCES `USER` (`id`);